### ISSUE TITLE
GTA: Possible to fix cycling weapons and radio

### ISSUE THREAD

**Issue by NotRacistBoi** [TheOfficialFloW/RemasteredControls#10]
I love these controls. My only gripe is when I’m walking around and I want to move my camera I use the right analog. That also cycles through my weapons so it can get annoying when I’m trying to look around and kee cycling through my gun and fist. Same thing while in a car. I’ll turn the radio off then go to look around and end up cycling through the stations. Anyway to unmap the dpad from right analog. Or at the very least stop this

**Comment by TheOfficialFloW** [comment]
Open Adrenaline Settings and choose Official Settings...
