### ISSUE TITLE
PPSSPP cheat possibility

### ISSUE THREAD

**Issue by dude98** [TheOfficialFloW/RemasteredControls#18]
Is there anyway you could convert parts of these into cheats for ppsspp? it has a right analog stick ability and peace walker already has a code, so you could be able to look it over and see if anything like it can be done for the other games, as what you are able to do with ppsspp is pretty good, allowing you to have both the super high resolution of an emulator, with the dual sticks of the vita.

**Comment by BurAndBY** [comment]
why, this plugins are made for PSVita's Adrenaline, and PPSSPP doesn't even have second thing in original.

**Comment by dude98** [comment]
PPSSPP is a psp emulator, and in it's controls settings it has a right analog config available. also, psvita's adrenaline is pretty much the same in that it lets you play psp games.
