### ISSUE TITLE
HID Mouse on PS TV

### ISSUE THREAD

**Issue by dbenoy** [TheOfficialFloW/RemasteredControls#2]
Maybe this is a super odd request, and honestly I don't expect it to get done, I'm mostly just super curious to find out if it's something that's feasible or not.

I wonder if these patches could be altered to provide nice smooth unaccelerated mouse aiming, possibly with keyboard support, too.

I'm imagining that would also be really cool in native Vita games with really clunky aiming, like Uncharted.

**Comment by TheOfficialFloW** [comment]
Not interested and don't abuse the issues section for requests please.

**Comment by dbenoy** [comment]
Where do they go?
